openapi: 3.0.0
info:
  title: TrueNAS RESTful API
  version: v2.0
servers:
- url: "https://{server}/api/v2.0"
  variables:
    server:
      default: truenas
      description: host name or ip
security:
- BasicAuth: []
- BearerAuth: []
paths:
  /disk:
    get:
      operationId: listDisks
      parameters:
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: count
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: sort
        required: false
        schema:
          type: string
        style: form
      - description: will also include expired disks
        explode: true
        in: query
        name: extra.include_expired
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: will not hide KMIP password for the disks
        explode: true
        in: query
        name: extra.passwords
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: "will query if disks support S.M.A.R.T. Only supported if resulting\
          \ disks count is not larger than one; otherwise, raises an error."
        explode: true
        in: query
        name: extra.supports_smart
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: will join pool name for each disk
        explode: true
        in: query
        name: extra.pools
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisksResponse'
          description: A list of disks
        "401":
          description: No authorization for this endpoint
      tags:
      - disk
  /disk/id/{id}:
    get:
      operationId: getDisk
      parameters:
      - description: Disk ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Disk'
          description: A disk
        "401":
          description: No authorization for this endpoint
        "404":
          description: Endpoint not found
      tags:
      - disk
    put:
      operationId: updateDisk
      parameters:
      - description: Disk ID
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateDisk_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Disk'
          description: A disk
        "401":
          description: No authorization for this endpoint
        "404":
          description: Endpoint not found
      tags:
      - disk
  /pool:
    get:
      operationId: listPools
      parameters:
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - explode: true
        in: query
        name: count
        required: false
        schema:
          type: boolean
        style: form
      - explode: true
        in: query
        name: sort
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolList'
          description: A list of pools
        "401":
          description: No authorization for this endpoint
      tags:
      - pool
components:
  parameters:
    LimitParam:
      explode: true
      in: query
      name: limit
      required: false
      schema:
        type: integer
      style: form
    OffsetParam:
      explode: true
      in: query
      name: offset
      required: false
      schema:
        type: integer
      style: form
    CountParam:
      explode: true
      in: query
      name: count
      required: false
      schema:
        type: boolean
      style: form
    SortParam:
      explode: true
      in: query
      name: sort
      required: false
      schema:
        type: string
      style: form
  responses:
    NotFound:
      description: Endpoint not found
    Unauthorized:
      description: No authorization for this endpoint
    Success:
      description: Operation succeeded
  schemas:
    AdvPowermgmt:
      enum:
      - DISABLED
      - "1"
      - "64"
      - "127"
      - "128"
      - "192"
      - "254"
      type: string
    Device:
      additionalProperties: true
      example:
        path: path
        disk: disk
        stats:
          key: ""
        children:
        - key: ""
        - key: ""
        name: name
        guid: guid
        device: device
        status: status
        unavail_disk:
          key: ""
      properties:
        name:
          type: string
        path:
          type: string
        guid:
          type: string
        status:
          type: string
        stats:
          additionalProperties: true
          type: object
        device:
          type: string
        disk:
          type: string
        children:
          items:
            additionalProperties: true
            type: object
          type: array
        unavail_disk:
          additionalProperties: true
          type: object
      type: object
    DisksResponse:
      items:
        $ref: '#/components/schemas/Disk'
      type: array
    Disk:
      additionalProperties: false
      example:
        rotationrate: 2
        bus: bus
        critical: 1
        transfermode: transfermode
        lunid: lunid
        subsystem: subsystem
        description: description
        type: type
        number: 0
        enclosure:
          number: 7
          slot: 9
        advpowermgmt: null
        informational: 5
        model: model
        devname: devname
        identifier: identifier
        expiretime: expiretime
        pool: pool
        togglesmart: true
        zfs_guid: zfs_guid
        kmip_uid: kmip_uid
        size: 6
        serial: serial
        hddstandby: null
        passwd: passwd
        name: name
        difference: 5
        supports_smart: true
        smartoptions: smartoptions
      properties:
        identifier:
          readOnly: true
          type: string
        name:
          readOnly: true
          type: string
        subsystem:
          readOnly: true
          type: string
        number:
          type: integer
        serial:
          readOnly: true
          type: string
        lunid:
          nullable: true
          type: string
        size:
          format: int64
          readOnly: true
          type: integer
        description:
          type: string
        transfermode:
          readOnly: true
          type: string
        hddstandby:
          $ref: '#/components/schemas/HDDStandby'
        advpowermgmt:
          $ref: '#/components/schemas/AdvPowermgmt'
        togglesmart:
          type: boolean
        smartoptions:
          type: string
        expiretime:
          nullable: true
          readOnly: true
          type: string
        critical:
          nullable: true
          type: integer
        difference:
          nullable: true
          type: integer
        informational:
          nullable: true
          type: integer
        model:
          nullable: true
          readOnly: true
          type: string
        rotationrate:
          nullable: true
          readOnly: true
          type: integer
        type:
          nullable: true
          readOnly: true
          type: string
        zfs_guid:
          nullable: true
          readOnly: true
          type: string
        bus:
          type: string
        devname:
          readOnly: true
          type: string
        enclosure:
          $ref: '#/components/schemas/Disk_enclosure'
        pool:
          nullable: true
          type: string
        passwd:
          type: string
        kmip_uid:
          nullable: true
          readOnly: true
          type: string
        supports_smart:
          nullable: true
          type: boolean
      required:
      - advpowermgmt
      - bus
      - critical
      - description
      - devname
      - difference
      - enclosure
      - expiretime
      - hddstandby
      - identifier
      - informational
      - lunid
      - model
      - name
      - number
      - pool
      - rotationrate
      - serial
      - size
      - smartoptions
      - subsystem
      - togglesmart
      - transfermode
      - type
      - zfs_guid
      type: object
    HDDStandby:
      enum:
      - ALWAYS ON
      - "5"
      - "10"
      - "20"
      - "30"
      - "60"
      - "120"
      - "180"
      - "240"
      - "300"
      - "330"
      type: string
    Pool:
      example:
        topology:
          special:
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          cache:
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          data:
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          log:
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          dedup:
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          spare:
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
          - path: path
            children:
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            - path: path
              disk: disk
              stats:
                key: ""
              children:
              - key: ""
              - key: ""
              name: name
              guid: guid
              device: device
              status: status
              unavail_disk:
                key: ""
            name: name
            guid: guid
            type: type
            status: status
        scan:
          key: ""
        is_decrypted: true
        encryptkey: encryptkey
        fragmentation: fragmentation
        status_detail: status_detail
        path: path
        size: 1
        freeing: 2
        encrypt: 6
        healthy: true
        encryptkey_path: encryptkey_path
        is_upgraded: true
        name: name
        guid: guid
        warning: true
        id: 0
        free: 5
        autotrim:
          key: ""
        status: status
        allocated: 5
      properties:
        id:
          type: integer
        name:
          type: string
        guid:
          type: string
        encrypt:
          type: integer
        encryptkey:
          type: string
        encryptkey_path:
          nullable: true
          type: string
        is_decrypted:
          type: boolean
        status:
          type: string
        path:
          type: string
        scan:
          additionalProperties: true
          type: object
        is_upgraded:
          type: boolean
        healthy:
          type: boolean
        warning:
          type: boolean
        status_detail:
          nullable: true
          type: string
        size:
          format: int64
          nullable: true
          type: integer
        allocated:
          format: int64
          nullable: true
          type: integer
        free:
          format: int64
          nullable: true
          type: integer
        freeing:
          format: int64
          nullable: true
          type: integer
        fragmentation:
          nullable: true
          type: string
        autotrim:
          additionalProperties: true
          type: object
        topology:
          $ref: '#/components/schemas/Pool_topology'
      required:
      - allocated
      - autotrim
      - encrypt
      - encryptkey
      - encryptkey_path
      - fragmentation
      - free
      - freeing
      - guid
      - healthy
      - id
      - is_decrypted
      - name
      - path
      - scan
      - size
      - status
      - status_detail
      - topology
      - warning
      type: object
    PoolList:
      items:
        $ref: '#/components/schemas/Pool'
      type: array
    VDev:
      additionalProperties: true
      example:
        path: path
        children:
        - path: path
          disk: disk
          stats:
            key: ""
          children:
          - key: ""
          - key: ""
          name: name
          guid: guid
          device: device
          status: status
          unavail_disk:
            key: ""
        - path: path
          disk: disk
          stats:
            key: ""
          children:
          - key: ""
          - key: ""
          name: name
          guid: guid
          device: device
          status: status
          unavail_disk:
            key: ""
        name: name
        guid: guid
        type: type
        status: status
      properties:
        guid:
          type: string
        name:
          type: string
        type:
          type: string
        path:
          nullable: true
          type: string
        status:
          type: string
        children:
          items:
            $ref: '#/components/schemas/Device'
          type: array
      required:
      - guid
      - name
      - path
      - stats
      - status
      - type
      type: object
    updateDisk_request:
      properties:
        number:
          type: integer
        lunid:
          nullable: true
          type: string
        description:
          nullable: true
          type: string
        critical:
          nullable: true
          type: integer
        difference:
          nullable: true
          type: integer
        informational:
          nullable: true
          type: integer
        hddstandby:
          $ref: '#/components/schemas/HDDStandby'
        advpowermgmt:
          $ref: '#/components/schemas/AdvPowermgmt'
        togglesmart:
          type: boolean
        supports_smart:
          type: boolean
        smartoptions:
          type: string
        passwd:
          type: string
      required:
      - advpowermgmt
      - critical
      - description
      - difference
      - hddstandby
      - informational
      - lunid
      - number
      - togglesmart
      type: object
    Disk_enclosure:
      additionalProperties: false
      example:
        number: 7
        slot: 9
      properties:
        number:
          type: integer
        slot:
          type: integer
      type: object
    Pool_topology:
      additionalProperties: true
      example:
        special:
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        cache:
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        data:
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        log:
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        dedup:
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        spare:
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
        - path: path
          children:
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          - path: path
            disk: disk
            stats:
              key: ""
            children:
            - key: ""
            - key: ""
            name: name
            guid: guid
            device: device
            status: status
            unavail_disk:
              key: ""
          name: name
          guid: guid
          type: type
          status: status
      properties:
        data:
          items:
            $ref: '#/components/schemas/VDev'
          type: array
        log:
          items:
            $ref: '#/components/schemas/VDev'
          type: array
        cache:
          items:
            $ref: '#/components/schemas/VDev'
          type: array
        spare:
          items:
            $ref: '#/components/schemas/VDev'
          type: array
        special:
          items:
            $ref: '#/components/schemas/VDev'
          type: array
        dedup:
          items:
            $ref: '#/components/schemas/VDev'
          type: array
      required:
      - cache
      - data
      - dedup
      - log
      - spare
      - special
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
    BearerAuth:
      bearerFormat: APIKey
      scheme: bearer
      type: http
